spring.datasource.driver-class-name: org.h2.Driver
spring.datasource.url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1
spring.datasource.username: sa
spring.datasource.password: sa
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml